language: node_js
node_js:
  - "10.6.0"
services:
  - postgresql
env:
  global:
    - export NODE_ENV=test

before_script:
  - npm install
  - psql -c 'drop if exist database travis_ci_test;' -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'CREATE TABLE users (id serial PRIMARY KEY, firstname varchar(100) not null, lastname varchar(100) not null, email varchar(100) not null, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW());' -U postgres -d travis_ci_test
  - psql -c "INSERT INTO users (firstname, lastname, email) VALUES ('Calory', 'Fish', 'fish@gmail.com');" -U postgres -d travis_ci_test
  - psql -c 'CREATE TABLE auth (id serial PRIMARY KEY, username varchar(50) not null, password varchar(500) not null, user_id integer REFERENCES users (id), created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW());' -U postgres -d travis_ci_test
  - psql -c "INSERT INTO auth (username, password, user_id) VALUES ('uche', '$2a$10$3ITQHk9oVRyXV6OvSmcS.eEslR5WKHlIOK8YA6obWWOl4h.lKttmS', 1);" -U postgres -d travis_ci_test
  - psql -c 'CREATE TABLE entries (id serial PRIMARY KEY, title varchar(100) not null, image_url varchar(1000) not null, note TEXT not null,is_favourite Boolean, user_id integer REFERENCES users (id), created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW());' -U postgres -d travis_ci_test

script:
  - npm run test

after_script:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
 