language: node_js
node_js:
  - "10.6.0"
services:
  - postgresql
env:
  global:
    - export NODE_ENV=test

before_script:
  - npm install

  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c 'CREATE TABLE  IF NOT EXISTS users (id serial PRIMARY KEY, firstname varchar(100) not null,lastname varchar(100) not null, email varchar(100) not null, created_at TIMESTAMP Default Now(),updated_at TIMESTAMP Default Now());' -U postgres -d travis_ci_test
  - psql -c 'CREATE TABLE  IF NOT EXISTS auth (id serial PRIMARY KEY, username varchar(250) not null, password varchar(250) not null, created_at TIMESTAMP Default Now(),updated_at TIMESTAMP Default Now(), user_id int, CONSTRAINT FK_UserAuth FOREIGN KEY (user_id) REFERENCES users(id));' -U postgres -d travis_ci_test
  - psql -c 'CREATE TABLE IF NOT EXISTS entries(id SERIAL PRIMARY KEY, title VARCHAR(255)  NOT NULL, note VARCHAR(255) NOT NULL,  is_favourite BOOLEAN DEFAULT false,image_url VARCHAR(255) DEFAULT NULL,created_at TIMESTAMP Default Now(),updated_at TIMESTAMP Default Now(),user_id int, CONSTRAINT FK_UserEntries FOREIGN KEY (user_id) REFERENCES users(id));' -U postgres -d travis_ci_test
  - psql -c "INSERT INTO users (firstname, lastname, email) VALUES ('Ismail','ibrahim', 'ismail@gmail.com');" -U postgres -d travis_ci_test
  - psql -c "INSERT INTO auth (username, password, user_id) VALUES ('fomuq1mypnw', '$2a$10$i3iS.zXHEJuOaGUcld7Kie9LLUO7tM7ZRg8xyNNCY1gsLieu7EyVm', 1);" -U postgres -d travis_ci_test
  - psql -c "INSERT INTO entries (title, note, image_url, user_id) VALUES ('Thisistitle', 'I lovemy job', 'image.png', 1);" -U postgres -d travis_ci_test

  
script:
  - npm run test

after_script:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
 