language: node_js
node_js:
  - "10.6.0"

env:
  global:
    - export NODE_ENV=test

before_script:
  - npm install

script:
  - npm run test

after_script:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
 